SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (SELECT CAR_ID 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE MONTH(START_DATE) IN (8, 9, 10) AND YEAR(START_DATE) = 2022
      GROUP BY CAR_ID 
      HAVING COUNT(*) >= 5)
      AND MONTH(START_DATE) IN (8, 9, 10) AND YEAR(START_DATE) = 2022
GROUP BY CAR_ID, MONTH(START_DATE)
HAVING COUNT(*) != 0
ORDER BY MONTH(START_DATE), CAR_ID DESC