SELECT FLAVOR
FROM (
    SELECT H.FLAVOR AS FLAVOR, RANK() OVER (ORDER BY H.TOTAL_ORDER + J.TOTAL_ORDER DESC) AS RANK
    FROM
        FIRST_HALF H
        INNER JOIN (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR
        ) J
        ON H.FLAVOR = J.FLAVOR
) TMP
WHERE RANK < 4
