SELECT
    A.AUTHOR_ID
    , A.AUTHOR_NAME
    , B.CATEGORY
    , SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM
    BOOK B
    , AUTHOR A
    , (
        SELECT BOOK_ID, SUM(SALES) AS SALES
        FROM BOOK_SALES
        WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
        GROUP BY BOOK_ID
    ) S
WHERE
    B.AUTHOR_ID = A.AUTHOR_ID
    AND B.BOOK_ID = S.BOOK_ID
GROUP BY
    A.AUTHOR_ID
    , A.AUTHOR_NAME
    , B.CATEGORY
ORDER BY
    A.AUTHOR_ID
    , B.CATEGORY DESC